language: php
php:
  - 7.2
  - nightly

before_script:
  - if [ "$TRAVIS_PHP_VERSION" != 'nightly' ]; then phpenv config-rm xdebug.ini; fi

install:
  - phpize
  - ./configure --enable-streams2
  - make

script:
  - php run-tests.php -p `which php` -d extension=`pwd`/modules/streams2.so -g "FAIL,XFAIL,BORK,WARN,LEAK,SKIP" --offline --show-diff --show-slow 1000 --set-timeout 120

after_failure:
  - cat tests/*.diff
